### ISSUE TITLE
Not working - fails silently

### ISSUE THREAD

**Issue by thomasfrobieter** [Cerzat43/vscode-twigcs#9] opened 2018-06-20 17:28 UTC
I have no idea whats wrong. I have installed Composer and installed allocine/twigcs globaly with composer. Also installed your VSCode plugin.

Its simply not working here. Errors in Twig are not highlighted nor mentioned in the "Problems"-Tab.

Have you any idea what could be wrong here?

Restarted VSCode, restarted Windows, reinstalled the plugin .. 

Its Windows 10, VSCode 1.24.1

Installed Composer Packages:
======================================
allocine/twigcs           v3.0.1             Checkstyle automation for Twig
asm89/twig-lint           dev-master 9ce57f6 Standalone twig linter.
pimple/pimple             v3.2.3             Pimple, a simple Dependency Injection Container
psr/container             1.0.0              Common Container Interface (PHP FIG PSR-11)
psr/log                   1.0.2              Common interface for logging libraries
symfony/console           v3.3.10            Symfony Console Component
symfony/debug             v3.3.10            Symfony Debug Component
symfony/finder            v3.3.10            Symfony Finder Component
symfony/polyfill-mbstring v1.6.0             Symfony polyfill for the Mbstring extension
twig/twig                 v1.35.0            Twig, the flexible, fast, and secure template language for PHP

**Comment by thomasfrobieter** [comment] 2018-06-21 12:09
If i try to run it in the console ("twigcs lint FOLDER") i get:

PHP Fatal error:  Declaration of Allocine\Twigcs\Compatibility\TwigLexer::tokenize(Twig_Source $source) must be compatible with Twig_LexerInterface::tokenize($code, $name = NULL) in C:\Users\XXX\AppData\Roaming\Composer\vendor\allocine\twigcs\src\Compatibility\TwigLexer.php on line 28

**Comment by adambernstein** [comment] 2018-08-14 15:17
Same issue here. Tried to set the executable path multiple different ways and no errors at all, but the linter won't start in any case.

**Comment by Cerzat43** [comment] 2018-10-26 19:44
Hi,
Is it possible tu update composer/twigcs and retry ?
I think the problem is fixed with https://github.com/allocine/twigcs/issues/43

**Closed as completed** 2019-01-29 10:33 UTC

**Comment by spchaplin** [comment] 2019-08-20 20:50
Hi, I'm having the same problem described above.  I have a system-wide install of twigcs version ^3.1 .  I can run twigcs from the command prompt to lint a file successfully.  However, I cannot get any linting visible in vs code for twig files, and nothing in the "problems" output.  Nothing happens differently than before the plugin was installed.

MacOS Mojave 10.14.5
Composer version 1.9.0
Using PHP version 7.3.7.  

I've also tried doing a project wide installation of twigcs in addition to the system wide installation, but with same result.  I've also tried specifying twigcs.executablePath in settings.json.

If I change the output in the debug console to show "Log(Extension Host)", I see the following line:

[2019-08-20 15:28:24.484] [exthost] [info] ExtensionService#_doActivateExtension cerzat43.twigcs {"startup":false,"activationEvent":"onLanguage:twig"}

That seems to be saying the extension is recognized and will activate when a *.twig file is loaded.  If there's any other information I can provide, please let me know.  In my list of language options, there's one called "HTML (Twig) (twig)" and this has the Twig icon next to it.  The second parentheses with "(twig)" is in gray and seems to indicate the file extension.  I'm wondering if your "Twigcs Linter" extension is being loaded but somehow never recognizing that a twig file has been displayed?

If you have any ideas, please let me know.  Thanks!

**Comment by adambernstein** [comment] 2019-08-20 21:31
@spchaplin I was able to get mine working recently in Twigcs Linter 1.1.0 by installing twigcs globally :
`composer global require friendsoftwig/twigcs`

Then in VSCode preferences, find `twigcs.executablePath` and **set it to the twigcs binary** from your global installation: 
`../path/to/your/global/Composer/vendor/bin/twigcs`

Hope that helps!

**Comment by spchaplin** [comment] 2019-08-20 22:13
Adam, thanks so much for the idea! I've added the following line to my settings.json:

"twigcs.executablePath": "/Users/myusername/.composer/vendor/bin/twigcs"

I can use that path to run the twigcs executable from command line successfully, e.g., 

$  /Users/myusername/.composer/vendor/bin/twigcs filetolint.twig
result: 
// l.19 c.41 : WARNING Unused macro import "buttons".
// l.20 c.39 : WARNING Unused macro import "forms".
// l.21 c.42 : WARNING Unused macro import "identity".
// l.22 c.37 : WARNING Unused macro import "svg".
// l.54 c.20 : ERROR A line should not end with blank space(s).

But it's still having no effect on vs code.  Anyone's ideas are welcomed, and thanks in advance!

**Comment by adambernstein** [comment] 2019-08-21 12:37
@spchaplin that's strange! I'm not on Mac, so I haven't tried this - but try escaping the '/' and using a backslash in the path instead in your settings.json:

`"twigcs.executablePath": "\\Users\\myusername\\.composer\\vendor\\bin\\twigcs"`

**Comment by spchaplin** [comment] 2019-08-21 22:21
Adam, many thanks for this suggestion, it's a good one.

I tried escaping as you suggested "//", and also tried escaping the forward slash in a separate attempt "\\/" , but with same result.  Other attempts included running vs code as administrator (sudo), and installing twigcs in a separate location (my home directory), then listing that path as the twig.executablePath in settings.json.  Also tried uninstalling the Twig 2 vs code extension in case that might be causing a conflict, and it's related entries in settings.json:

  "files.associations": {
    "*.html": "twig",
  },
  "emmet.includeLanguages": {
    "twig": "html"
  }

Still the same result.  If you or anyone else have further ideas, I'm open to them, and thanks for the ideas thus far.
